### ISSUE TITLE
create an index MeilisearchCommunicationError for docker

### ISSUE THREAD

**Issue by Lawliet-Chan** [meilisearch/meilisearch-go#448]
**Description**
my process in A docker used meilisearch-go to connect the MeiliSearch docker(just name it B docker) with `:7700`, but it shows:
```
MeilisearchCommunicationError unable to execute request (path \"POST /indexes\" with method \"CreateIndex\"): dial tcp4 127.0.0.1:7700: connect: connection refused
``` 
My docker-compose.yml is:
```
version: '3'
services:
  uask:
    image: uask:0.1
    restart: unless-stopped
    container_name: uask
    ports:
      - "7999:7999"
      - "8999:8999"
    networks:
      - app-network
    volumes:
      - ./uask:/uask
      - ./yu.toml:/config/yu.toml:ro
      - ./poa.toml:/config/poa.toml:ro
    depends_on:
      - meili

  meili:
    image: getmeili/meilisearch:v1.2
    restart: unless-stopped
    container_name: meili
    ports:
      - "127.0.0.1:7700:7700"
    networks:
      - app-network
    volumes:
      - ./meili:/data.ms

networks:
  app-network:
    driver: bridge
```
I am sure that the meiliSearch works because I use `curl` to create an index to the meiliSearch docker locally , seems works.
How can I fix it?  

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: mac but in docker  getmeili/meilisearch:v1.2
- Meilisearch version: v1.2
- meilisearch-go version: v0.24.0
