### ISSUE TITLE
Add CI tests on different go versions

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-go#98]
As for now, `go.mod` defines go version to `1.12`. But the CI can test if this builds and runs on different versions in a very simple way, by using an Strategy Matrix in GitHub Actions:

```yaml
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.15', '1.12' ]
    name: Go ${{ matrix.go }} tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
```

This should be tested in https://github.com/meilisearch/meilisearch-go/blob/master/.github/workflows/go.yml
